### ISSUE TITLE
too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by PlasticBagBand** [Human9000/nd-Mamba2-torch#13]
作者你好，在我使用ex_vssd.py中的VMAMBA2Block进行一张2d推理的时候，会报这个错误
![image](https://github.com/user-attachments/assets/0f7d8977-7a7e-4dcf-ae36-f1b7127d089e

![image](https://github.com/user-attachments/assets/7b0d87b1-64a4-4b02-950d-35966fa74cbe)

![image](https://github.com/user-attachments/assets/71897cfd-2be7-4b75-ba02-cfa428a3ae0d)

请问是怎么回事？

还有一个疑问，在mamba2的forward中直接return u 导致后面的代码运行不到，应该是这样的吗？谢谢
![image](https://github.com/user-attachments/assets/be963793-7884-4bfb-b174-e64d2c466f43)

**Comment by PlasticBagBand** [comment]
![image](https://github.com/user-attachments/assets/9b324039-629d-4661-a1d0-9395c51869f5)
报这个错误

**Comment by Human9000** [comment]
你好，感谢你的提问。
根据问题显示，你输入的数据的shape不正确，正确的格式为 Shape[batch, length, channles]。
项目中有提供样例，请阅读 https://github.com/Human9000/nd-Mamba2-torch/blob/main/demo/test_build_net.py

**Comment by PlasticBagBand** [comment]
成功解决了，谢谢大佬
