### ISSUE TITLE
Why should it return here?

### ISSUE THREAD

**Issue by Xuanyaiiii** [Human9000/nd-Mamba2-torch#16]
https://github.com/Human9000/nd-Mamba2-torch/blob/d3e42e2821ab28f9765c4c33ea47435e56ee0374/torchnssd/ex_vssd_cls_seg.py#L601

Could you please tell me the reason? Thank you very much.

**Comment by Human9000** [comment]
Thank you very much for your feedback. 
This is a problem left over from the debugging work at that time, and I will fix it quickly.

**Comment by Xuanyaiiii** [comment]
Thank you for making such excellent work open source. Thank you so much.
