### ISSUE TITLE
ex_vssd.py文件中Mamba2模块forward过程

### ISSUE THREAD

**Issue by starduct** [Human9000/nd-Mamba2-torch#22]
您好，首先非常感谢您的工作。

我在调用ex_vssd.py时，发现其中Mamba2模块的forward过程被跳过了。定位到代码的第562行，您大概是忘记注释掉测试时使用的代码，输入向量被直接返回了。

**Comment by Human9000** [comment]
非常感谢你的反馈，我已经在最新版本中修复了这个问题，可以查看最新版本的ex_vssd.py的代码。
